id: IC545BD55
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T10:15:16+00:00'
last_modified: '2022-06-07T15:19:06.271049+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG9301
  title: མེས་པོའི་ཞལ་ལུང་ལས་བཤད་རྒྱུད་ཀྱི་ཟིན་ཐོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessRestrictedByTbrc
  restrictedInChina: false
  base:
    14A9:
      image_group_id: I1KG9392
      title: ''
      total_pages: 308
      order: 1
      base_file: 14A9.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
