id: P001832
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG9301
  title: མེས་པོའི་ཞལ་ལུང་ལས་བཤད་རྒྱུད་ཀྱི་ཟིན་ཐོ།
  author: ''
  volumes:
    b8a9c0c44e994591825dd4314fb6b12f:
      image_group_id: I1KG9392
      title: ''
      volume_number: 1
      total_pages: 308
      base_file: v001.txt
